# Auto-generated by asn1ate v.0.6.0 from controls.asn1
# (last modified on 2024-08-27 06:00:27.274074)

from pyasn1.type import univ, char, namedtype, namedval, tag, constraint, useful


maxInt = univ.Integer(2147483647)


class PagedResultsControlValue(univ.Sequence):
    pass


PagedResultsControlValue.componentType = namedtype.NamedTypes(
    namedtype.NamedType('size', univ.Integer().subtype(subtypeSpec=constraint.ValueRangeConstraint(0, maxInt))),
    namedtype.NamedType('cookie', univ.OctetString())
)


class SDFlagsRequestValue(univ.Sequence):
    pass


SDFlagsRequestValue.componentType = namedtype.NamedTypes(
    namedtype.NamedType('flags', univ.Integer())
)


class StatsResponseValueV3(univ.Sequence):
    pass


StatsResponseValueV3.componentType = namedtype.NamedTypes(
    namedtype.NamedType('threadCountTag', univ.Integer()),
    namedtype.NamedType('threadCount', univ.Integer()),
    namedtype.NamedType('callTimeTag', univ.Integer()),
    namedtype.NamedType('callTime', univ.Integer()),
    namedtype.NamedType('entriesReturnedTag', univ.Integer()),
    namedtype.NamedType('entriesReturned', univ.Integer()),
    namedtype.NamedType('entriesVisitedTag', univ.Integer()),
    namedtype.NamedType('entriesVisited', univ.Integer()),
    namedtype.NamedType('filterTag', univ.Integer()),
    namedtype.NamedType('filter', univ.OctetString()),
    namedtype.NamedType('indexTag', univ.Integer()),
    namedtype.NamedType('index', univ.OctetString()),
    namedtype.NamedType('pagesReferencedTag', univ.Integer()),
    namedtype.NamedType('pagesReferenced', univ.Integer()),
    namedtype.NamedType('pagesReadTag', univ.Integer()),
    namedtype.NamedType('pagesRead', univ.Integer()),
    namedtype.NamedType('pagesPrereadTag', univ.Integer()),
    namedtype.NamedType('pagesPreread', univ.Integer()),
    namedtype.NamedType('pagesDirtiedTag', univ.Integer()),
    namedtype.NamedType('pagesDirtied', univ.Integer()),
    namedtype.NamedType('pagesRedirtiedTag', univ.Integer()),
    namedtype.NamedType('pagesRedirtied', univ.Integer()),
    namedtype.NamedType('logRecordCountTag', univ.Integer()),
    namedtype.NamedType('logRecordCount', univ.Integer()),
    namedtype.NamedType('logRecordBytesTag', univ.Integer()),
    namedtype.NamedType('logRecordBytes', univ.Integer())
)


